### ISSUE TITLE
Executing MinLabel/SlurCutter as Admin

### ISSUE THREAD

**Issue by overdramatic** [openvpi/MakeDiffSinger#3]
Hi!
I use a modded version of Win11 (Ghost Spectre) and, by default, my user is an Admin.
Could the warning on MinLabel and SlurCutter be changed so they don't kill the application when hitting "OK"?

**Comment by yqzhishen** [comment]
Neither using non-official Windows distributions nor running applications as Admin user is recommended.

If you really want to start the application, then add `--allow-root` command-line option
