### ISSUE TITLE
Typo in forced alignment README

### ISSUE THREAD

**Issue by medioqrity** [openvpi/MakeDiffSinger#6]
> Run:
>
> `python build_dataset.py --wav path/to/your/segments/ --tg path/to/final/textgrids/ --dataset path/to/your/dataset/`

According to [this line](https://github.com/openvpi/MakeDiffSinger/blob/main/acoustic_forced_alignment/build_dataset.py#L14), the argument should be `wavs` instead of `wav`. The correct command should be `python build_dataset.py --wavs path/to/your/segments/ --tg path/to/final/textgrids/ --dataset path/to/your/dataset/`.

**Comment by yqzhishen** [comment]
Thanks for catching this, the typo has been fixed.
